#!/bin/bash
# This script generates ephemeral secrets and starts the local development environment.

echo "Generating ephemeral secrets for this session..."

# Generate random, secure strings for secrets
MONGO_PASS=$(openssl rand -hex 16)
FLASK_KEY=$(openssl rand -hex 32)

# Create a temporary .env file for Docker Compose to use.
# This file is git-ignored and will be overwritten on each run.
echo "Creating temporary .env file..."
cat > .env << EOL
# This is a temporary file generated by deploy-local.sh
# Do NOT commit this file.
MONGO_PASSWORD=${MONGO_PASS}
FLASK_SECRET_KEY=${FLASK_KEY}
EOL

echo "Secrets generated. Starting local deployment with Docker Compose..."

# Inform the user what the password is for this session, in case they need to connect manually.
echo "-----------------------------------------------------------------"
echo "MongoDB Password for this session: ${MONGO_PASS}"
echo "-----------------------------------------------------------------"

# Ensure the data directories exist
mkdir -p data/mongo
mkdir -p data/ollama

# Start the services. Docker Compose will automatically read the .env file.
docker-compose up --build
