#!/bin/bash
# This script generates ephemeral secrets and starts the local development environment.

# Exit immediately if a command exits with a non-zero status.
set -e
# Print each command to the terminal before executing it (for debugging).
set -x

echo "--- SCRIPT START ---"

echo "Generating ephemeral secrets for this session..."

# Generate random, secure strings for secrets
MONGO_PASS=$(openssl rand -hex 16)
FLASK_KEY=$(openssl rand -hex 32)

echo "--- SECRETS GENERATED (visible in script) ---"
echo "MONGO_PASS=${MONGO_PASS}"
echo "FLASK_KEY=${FLASK_KEY}"

# Create a temporary .env file for Docker Compose to use.
# This is a safer way to write the file that avoids shell issues.
echo "Creating temporary .env file..."
printf "# This is a temporary file generated by deploy-local.sh\nMONGO_PASSWORD=%s\nFLASK_SECRET_KEY=%s\n" "$MONGO_PASS" "$FLASK_KEY" > ./.env

echo "--- VERIFYING .env FILE CONTENTS ---"
cat ./.env
echo "------------------------------------"

# Inform the user what the password is for this session for manual connection.
echo "INFO: The MongoDB Password for this session is: ${MONGO_PASS}"

# Ensure the data directories exist
mkdir -p data/mongo
mkdir -p data/ollama

# Start the services, explicitly telling Docker Compose to use our .env file.
echo "--- RUNNING DOCKER COMPOSE ---"
docker-compose --env-file ./.env up --build

# Turn off debugging flags when the script is done.
set +x
set +e
