#!/bin/bash
# This script generates ephemeral secrets, writes them to a .env file, 
# and starts the local development environment.

# Exit immediately if a command exits with a non-zero status.
set -e
# Print each command to the terminal before executing it (for debugging).
set -x

echo "--- SCRIPT START ---"

echo "1. Generating ephemeral secrets for this session..."
MONGO_PASS=$(openssl rand -hex 16)
FLASK_KEY=$(openssl rand -hex 32)

echo "2. Writing secrets to .env file..."
# This uses printf for maximum compatibility. The file is created in the current directory.
printf "# This is a temporary file generated by deploy-local.sh\nMONGO_PASSWORD=%s\nFLASK_SECRET_KEY=%s\n" "$MONGO_PASS" "$FLASK_KEY" > ./.env

echo "3. Verifying contents of .env file:"
# We will now print the file to ensure the secrets are there.
cat ./.env
echo "------------------------------------"


echo "4. Informing user of the generated password for this session."
echo "INFO: The MongoDB Password for this session is: ${MONGO_PASS}"


echo "5. Ensuring data directories exist..."
mkdir -p data/mongo
mkdir -p data/ollama

echo "6. Running Docker Compose with the generated .env file..."
# We explicitly point to the .env file to avoid any ambiguity.
docker-compose --env-file ./.env up --build

echo "--- SCRIPT COMPLETE ---"
# Turn off debugging flags when the script is done.
set +x
set +e
