
x-common-env: &common-env
  FLASK_ENV: development
  MONGO_URI: mongodb://root:example@mongo:27017/intellidocs?authSource=admin
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
  OLLAMA_HOST: http://ollama:11434
  CHAT_MODEL_NAME: phi3:mini
  EMBEDDINGS_MODEL_NAME: BAAI/bge-large-en

services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: ui
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    depends_on:
      - mongo
      - redis
      - ollama
    environment: *common-env
    networks:
      - app-network
    volumes:
      - pip-cache:/root/.cache/pip

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A main.celery worker --loglevel=info
    container_name: celery-worker
    depends_on:
      - redis
      - ollama
    environment: *common-env
    networks:
      - app-network
    volumes:
      - pip-cache:/root/.cache/pip

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    networks:
      - app-network
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  ollama-data:
  pip-cache:
