import logging
from app.celery_worker import celery

logger = logging.getLogger(__name__)

@celery.task(bind=True, name='execute_playbook_subtask')
def execute_playbook_subtask(self, step_config: dict, context: dict, doc_id: str):
    """
    A dedicated Celery task to execute a single playbook step.

    This is used by control flow steps like ParallelStep to farm out work
    to the cluster. It runs one step and returns the resulting 'outputs'
    from its context.
    """
    db = self.db
    step_name = step_config.get('name', 'Unnamed Sub-Task Step')
    logger.info(f"Executing sub-task for step '{step_name}' for doc_id {doc_id}.")

    # We need a minimal PlaybookExecutor-like object for the step to use.
    # Since this task only runs one step, the executor's `execute_steps` method
    # can be simplified or omitted if no sub-steps call it.
    from app.playbook_worker import PlaybookExecutor
    executor = PlaybookExecutor(db, doc_id)

    step_type = step_config.get('type')
    plugin = executor.step_plugins.get(step_type)

    if plugin:
        plugin.execute(step_config, context, db, doc_id, executor)
        # Return only the 'outputs' dictionary generated by this step
        return context.get('outputs', {})
    else:
        logger.error(f"Unknown step type '{step_type}' in sub-task for step '{step_name}'.")
        return {}