import logging
from app.celery_worker import celery
from app.ai_models import get_llm
from app.blueprints.chat import get_global_agent_executor
from app.stream import publish_chat_token, publish_chat_end
from langchain.callbacks.base import BaseCallbackHandler

logger = logging.getLogger(__name__)

class SocketIOStreamCallback(BaseCallbackHandler):
    """
    Callback handler for streaming LangChain results to a Socket.IO client.
    """
    def __init__(self, session_id: str):
        super().__init__()
        self.session_id = session_id

    def on_llm_new_token(self, token: str, **kwargs) -> None:
        """
        This method is called for each new token generated by the LLM.
        It publishes the token to the specific client's room.
        """
        publish_chat_token(self.session_id, token)

@celery.task(bind=True, name='global_chat_agent_task')
def global_chat_agent_task(self, query: str, session_id: str):
    """
    Celery task to run the global chat agent asynchronously and stream results.
    """
    logger.info(f"Global Chat Agent Task started for session {session_id} with query: '{query[:50]}...'")
    
    try:
        # Create a callback manager with our custom streaming handler
        callback_manager = [SocketIOStreamCallback(session_id)]
        
        # Get the LLM and Agent Executor
        # We pass the callback manager to the LLM so it can stream tokens.
        llm = get_llm(callbacks=callback_manager)
        agent_executor = get_global_agent_executor(llm)

        # Invoke the agent. The streaming will happen automatically via the callback.
        # The final 'output' will be streamed token by token.
        agent_executor.invoke({"input": query})

    except Exception as e:
        logger.error(f"Error in Global Chat Agent Task for session {session_id}: {e}", exc_info=True)
        # Notify the client that an error occurred
        error_message = "Sorry, I encountered an error while processing your request."
        publish_chat_token(session_id, error_message)
    
    finally:
        # Always send an end-of-stream signal to the client
        # This tells the frontend that the response is complete.
        logger.info(f"Global Chat Agent Task finished for session {session_id}.")
        publish_chat_end(session_id)