server {
  listen 80;
  server_name localhost;

  # Serve the static files for the Angular app
  root /usr/share/nginx/html/intelli-docs;
  index index.html index.htm;

  # For all other locations, try to serve the file, then a directory,
  # and finally fall back to index.html for client-side routing.
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Proxy API requests to the backend Flask container
  location /api {
    proxy_pass http://api:8080;
  }
}